### ISSUE TITLE
Timer restarting upon deploy

### ISSUE THREAD

**Issue by rasmusdencker** [Writech/node-red-contrib-controltimer#5]
Hey there,

Thanks for a very useful node! I use it for several different cases. I noticed that if a timer is running and you re-deploy the flow, the timer stops. I'm just curious to know if that behaviour is by design or unintended?

**Comment by Writech** [comment]
Glad to hear you found this node useful!

I'm afraid what you're describing is the limitation of Node-RED platform. An excerpt from Node-RED [_Creating your first node_](https://nodered.org/docs/creating-nodes/first-node) page:

> Nodes get created when a flow is deployed, they may send and receive some messages whilst the flow is running and **they get deleted when the next flow is deployed**.

From my personal experience the same thing happens with other timer node implementations as well - they get deleted and recreated upon deployment of a new flow or a modification of it. The same thing happens with nodes that establish some sort of network connection to some entity - upon deployment connection gets dropped and new connection is created. 

Perhaps there is some mechanism to save the state of nodes before deploying a new flow and restore it in the freshly deployed flow that I'm currently not aware of.

**Comment by Writech** [comment]
I may have found a way to keep the timer in it's running state if the flow it's in gets redeployed. But I want to do it right and it takes some time. I try to do it in a way to allow the user of the node to choose whether they want the timer to continue running from the remaining duration when the flow was redeployed or to reset the duration and start the duration from zero.
Will release new version when ready.

**Comment by sanderlv** [comment]
Hi, I also stumbled on this issue when just an hour ago I found this node and I am very happy with it so far! Exactly what I needed!

I have the issue that after redeployment the time is not "kept". sometimes it keeps the time and sometimes it does simply not respond on CONTINUE but only again on START... Is that intended behavior?
