### ISSUE TITLE
TypeError: done is not a function

### ISSUE THREAD

**Issue by MartinTerp** [Writech/node-red-contrib-controltimer#8]
Hi

I have a simple flow, where I input START to your node, I get:

```
1/30/2021, 5:19:35 PMnode: 3555ea0f.3e2936
msg : error
"TypeError: done is not a function"
```

**Comment by Writech** [comment]
What Node-RED version are you using? I'm using v1.2.9 and the node works without any issue.

**Comment by MartinTerp** [comment]
it was the version :D 
thx
